[package]
name = "mga"
version = "0.0.0"
edition = "2021"

[dependencies]
mga-sys = { path = "mga-sys", version = "0.0.0" }

[features]
default = ["export-sys"]
export-sys = []

[workspace]
members = ["mga-sys"]
