[package]
name = "mga"
version = "0.0.0"
edition = "2021"

[dependencies]
mga-sys = { path = "mga-sys", version = "0.0.0" }

[features]
default = ["export-sys"]

# Use malloc backend
malloc = ["mga-sys/malloc"]

# Re-export the mga-sys crate
export-sys = []

[workspace]
members = ["mga-sys"]
